### ISSUE TITLE
Attempting to create an alias named ".." results in panic.

### ISSUE THREAD

**Issue by shindakun** [mattmorganpdx/talias#1]
talias crashes when you attempt to create an alias named .. as it should since . and .. may want to do some light validation of alias names.

```bash
steve@~$ talias -a ..
9  |  talias -l
10  |  talias -L
11  |  ls -al
12  |  cd ..
13  |  cat .viminfo
14  |  pwd
15  |  talias -d
16  |  exit
17  |  cd ~
18  |  talias -l
Enter command number (or 'p' for previous 10) : 12
panic: open /home/steve/.talias: is a directory

goroutine 1 [running]:
main.check(0x58b420, 0xc42000e690)
        /home/steve/talias/talias.go:108 +0x4a
main.addAliasScript(0xc420014350, 0x6, 0xc, 0x0, 0x7fffdf670a79, 0x2, 0x410b00)
        /home/steve/talias/talias.go:239 +0xfd
main.addAlias(0xc42000e660, 0xc42000e630)
        /home/steve/talias/talias.go:270 +0x1d6
main.main()
        /home/steve/talias/talias.go:343 +0x15a
```

**Comment by shindakun** [comment]
Of course, cd in the script isn't going to work anyway so...
